### PR TITLE
Refactoring of include directive of header files 

### PR DESCRIPTION
**Pull request by atztogo**
- `#include "alm.h"` were removed from most of header files. Instead more include directives were written for respective Class definitions.

- `typedef std::vector<std::map<unsigned int, double>> ConstraintSparseForm;` in `constraint.h` was removed. There is duplicate typedef in `fcs.h`, which is included in `constant.h` now and `rref.h` as well. I wanted to preserved that in `constrain.h` but it was not possible due to the header file dependency. Maybe this typedef will be moved some other header file that contains utility definitions like `constants.h`.

- Note that this pull request also includes the change corresponding to #9 with replacing `get_cell` by `get_supercell`.

### CODE REVIEW

**Comment by ttadano** [comment]
The new version #10 works when used as API but crashes when used via the command line as
`$ alm < ALM.in > ALM.out`

This bug can be fixed by adding the following line in ``System::init``:
```
set_cell(lavec, nat, nkd, kd, xcoord);
```
Can you fix it? I'll merge the PR when this issue is resolved.

**Comment by atztogo** [comment]
Thanks. After adding `set_cell`, I got another segmentation fault. I could not solve this issue quickly. Instead I am now working on `InputSetter` and `InputParser` to more decoulple from other classes. Could you test this branch, https://github.com/atztogo/ALM/tree/modify-System? If this works (it semms working for suggest), I will make another pull request by closing this pull request. The design direction of `InputSetter` and `InputParser` is to access ALM only via API though currently they touch almost directly internal variables (mind that this was made by me, sorry!), which is dangerous and less easy to control.

**Comment by ttadano** [comment]
The modify-System branch version works correctly both via API and command line! Thank you.

**Comment by ttadano** [comment]
Thank you. I've merged it.

**Pull request merged**
